pages/history.tsx
pages/vest.tsx
src/components/history/HistorySectionIntro.tsx
src/components/vest/VestDealTokens.tsx
src/components/vest/VestSectionIntro.tsx
src/hooks/requiredConnection.tsx

Add Connect Wallet on History and Vest sections

---

src/components/sidebar/MyPools.tsx

Sidebar - My Pools - Wrong numbers after disconnecting wallet

---

src/components/toast/Toast.tsx
src/components/toast/ToastComponent.tsx

Fix toast size

---

src/components/pools/actions/Approve.tsx

(BUG) Approve token button should be disabled if no userBalance

---

src/hooks/aelin/useAelinPoolStatus.ts

(BUG) PoolAction is incorrect on WithdrawUnredeemed

---

src/components/pools/common/Summary.tsx
src/hooks/aelin/useAelinCreateDeal.tsx
src/hooks/aelin/useAelinCreatePool.tsx

(FEAT) Add token symbol icon and etherscan link

---

src/components/vest/VestDealTokens.tsx

Vest Section - Add empty state

---

src/components/history/DealsAccepted.tsx
src/components/history/DealsFunded.tsx
src/components/history/DealsSponsored.tsx
src/components/history/Deposits.tsx
src/components/history/Vests.tsx
src/components/history/Withdraws.tsx
src/components/history/common/TableWrapper.tsx

History Section - Add empty state

---

src/components/pools/deal/DealInformation.tsx
src/hooks/aelin/useAelinDealUserStats.tsx

Add Amount Accepted to User Stats cell

---

src/hooks/aelin/useAelinPoolStatus.ts

(Bug) User action incorrect when clicking on notification HolderSet

---

src/components/common/DynamicDeadline.tsx
src/components/pools/actions/AcceptDeal.tsx
src/components/pools/common/Timeline.tsx
src/components/pools/deal/DealInformation.tsx
src/components/pools/deal/VestingInformation.tsx
src/components/pools/list/List.tsx
src/components/pools/main/PoolInformation.tsx
src/components/vest/VestDealTokens.tsx
src/hooks/aelin/useAelinPoolStatus.ts
src/queries/pools/fragments.ts
src/utils/date.ts
types/aelinPool.ts

Fix Deadline Bars (Info & Timeline)

---

src/components/pools/deal/DealCreateStepInput.tsx

(Fix) Showing to many (unnecessary) decimals

---

package.json
src/components/common/CollapsibleBlock.tsx
yarn.lock

Responsiveness - Timeline & Sidebar are now initialized as collapsed on Mobile version

---

src/components/stake/StakeGrid.tsx

Responsiveness - Stake page

---

src/components/pools/actions/Vest/Vest.tsx
src/hooks/aelin/useAelinVestingDeals.tsx
src/queries/pools/vestingDeal.ts
src/queries/pools/vestingDeals.ts

Use lastClaim to deduce if there are any remaining tokens to claim

---

src/components/pools/deal/DealInformation.tsx
src/components/pools/main/PoolInformation.tsx
src/hooks/aelin/useAelinPool.tsx
src/utils/aelinPoolUtils.ts

(FEAT) Add extra information to PoolInfo section

---

src/components/pools/actions/WithdrawUnredeemed.tsx

Improve withdraw unredeemed action box

---

src/components/pools/actions/Vest/Vest.tsx
src/components/pools/actions/Vest/VestingPeriod.tsx
src/queries/pools/vestingDeal.ts

Add My deal total to Vesting Period box

---

src/components/pools/whitelist/UploadWhiteListCsv.tsx
src/components/pools/whitelist/WhiteListModal.tsx
src/hooks/aelin/useAelinCreatePool.tsx

(Fix) Whitelist modal - Max allocation amount

---

src/components/common/Modal.tsx

(Fix) Whitelist Upload CSV doesn't work

---

src/components/pools/actions/FundDeal.tsx
src/components/pools/actions/HolderDeposit.tsx

Improve fund deal action box

---

src/components/pools/actions/FundDeal.tsx

(Bug) Change Fund Deal description is holder == sponsor

---

src/components/layout/RightTimelineLayout.tsx

(Fix) Increase Box size so text fits

---

src/hooks/aelin/useAelinPoolStatus.ts

Closes #480 
This PRs improves UX by pulling data from the SG every 5s.

(enhance) Takes too long for changes to be reflected

---

src/components/stake/StakeGrid.tsx
src/components/stake/StakeSection.tsx
src/utils/getExplorerUrl.ts

Stake Page - Add contract links

---

src/components/pools/PoolMain.tsx
src/components/pools/deal/DealInformation.tsx

(Fix) Add notice text if cap reached

---

src/components/stake/StakeTabContent.tsx
src/constants/misc.ts
src/utils/stake/getGelatoStakingRewards.ts

Stake page - Fix AELIN/ETH pool

---

src/components/pools/common/TokenIcon.tsx
src/components/section/PageTitle.tsx
src/hooks/aelin/useAelinPoolStatus.ts

(Bug) Fix warning react

---

src/components/section/PageTitle.tsx
src/hooks/aelin/useAelinPoolStatus.ts

(Bug) Fix warning

---

src/hooks/aelin/useAelinPoolStatus.ts
src/hooks/aelin/useUserAllocationStats.ts

Reverts AelinXYZ/aelin-frontend-v2#485

Revert "(Fix) Vesting Tab action"

---

src/hooks/aelin/useAelinPoolStatus.ts

(Fix) Vesting tab action

---

src/components/pools/PoolMain.tsx
src/hooks/aelin/useAelinPoolStatus.ts

(Fix) If an investor does not invest in the pool the action box should not display Accept/Withdraw tabs

---

src/hooks/aelin/useAelinPool.tsx
src/utils/aelinPoolUtils.ts

Fix deal tokens accepted

---

pages/stake.tsx
src/components/stake/StakeInfo.tsx
src/components/stake/StakeSection.tsx

* Fix L1 Stake Box
* remove unused line

Fix L1 Stake Box (#526)

---

pages/pool/create.tsx
src/components/pools/whitelist/WhiteListModal.tsx

(Fix) The number of decimals allowed in the whitelisting input allocation should be <= investment token decimals

---

src/components/pools/actions/Vest/Vest.tsx
src/constants/misc.ts
src/constants/pool.ts
src/hooks/aelin/useAelinVestingDeals.tsx
src/utils/isFirstAelinPool.ts

* Disable vest for first aelin pool
* change address

Disable vest for first aelin pool (#536)

---

src/components/pools/list/List.tsx
src/components/pools/list/Vouched.tsx
src/components/pureStyledComponents/common/Table.tsx
src/hooks/aelin/useAelinPools.tsx

I also removed the $ symbol, it doesn't make sense to be there since the investment pool can be in any token.

Add total deposited column to main table

---

src/components/assets/Search.tsx
src/components/pools/whitelist/nft/NftCollection.tsx
src/components/pools/whitelist/nft/NftIdSelector.tsx
src/components/pools/whitelist/nft/NftsMinimumAmounts.tsx
src/components/pools/whitelist/nft/nftWhiteListReducer.tsx
src/components/pools/whitelist/nft/useNftCollectionList.tsx

NFT ID selector

---

src/components/pools/actions/ReleaseFunds.tsx
src/components/stake/StakeGrid.tsx
src/components/stake/StakeSection.tsx

Remove APY from Stake section

---

src/components/pools/whitelist/nft/NftCollection.tsx
src/components/pools/whitelist/nft/NftCollectionsSection.tsx
src/components/pools/whitelist/nft/NftWhiteList.tsx
src/components/pools/whitelist/nft/NftsMinimumAmounts.tsx
src/components/pools/whitelist/nft/nftWhiteListReducer.tsx
src/components/pools/whitelist/nft/useNftCollectionList.tsx

Replaced NFT ID selector with input + added fields validation
Closes #565

AELIP-15: Change NFT ID input logic

---

src/components/sidebar/AelinData.tsx

Staking page improvements

---

src/abis/AelinDeal.json
src/abis/AelinPool.json
src/abis/AelinPoolCreate.json
src/constants/contracts.ts
src/hooks/aelin/useAelinCreatePool.tsx
src/hooks/contracts/useAelinPoolCreateTransaction.tsx

Only includes pool creation as we know them, not NFT pools yet

AELIP-15: Adapt pool creation to match with new contracts

---

src/components/pools/PoolMain.tsx
src/components/pools/list/List.tsx
src/hooks/aelin/useAelinPools.tsx
src/utils/aelinPoolUtils.ts

AELIP-15: Adapt pool pages

---

pages/api/nft/[chainId]/[collectionAddress].ts
src/components/pools/actions/Invest/NftMedia.tsx
src/components/pools/whitelist/nft/NftCollectionAttribute.tsx
src/components/pools/whitelist/nft/NftCollectionInput.tsx
src/controllers/nft/index.ts
src/services/nft/index.ts

Adds back a controller to get Optimism NFT (Quixotic) data if the input is an address.
Also fixes some Image issues

[Bug] get nft quixotic by address

---

src/hooks/aelin/useNftUserAllocation.tsx
src/providers/nftSelectionProvider.tsx
src/services/nft/index.ts

Solve bugs (investor flow => Nft selection) for deals with multiple collections

[Bug] multiple collections selection

---

src/components/pools/actions/Invest/NftsPickerModal.tsx
src/constants/contracts.ts
src/hooks/aelin/useUserNftsByCollections.tsx
src/providers/nftSelectionProvider.tsx

AELIP-15 - [Bug] Show not be able to selectNft if blacklisted

---

src/components/pools/actions/Invest/NftsPickerModal.tsx

AELIP-15: Show scrollbar only when needed

---

src/components/pools/actions/Deposit.tsx
src/components/pools/actions/Invest/NftsPickerModal.tsx
src/hooks/aelin/useNftUserAllocation.tsx

AELIP-15: [FEAT] allocation exceeded error

---

src/services/nft/index.ts

This PR solves the issue of the NftSelection Modal showing collections not relevant to the pool.

AELIP-15: [Bug] Show relevant collections

---

src/components/pools/actions/Invest/NftsPickerModal.tsx
src/hooks/aelin/useUserNftsByCollections.tsx

This PR solves the problem of multiple NFT being selected by only clicking one

AELIP-15: [Bug] Multiple nfts selected

---

src/components/pools/whitelist/nft/nftWhiteListReducer.tsx

AELIP-15: [Bug] Should not be possible to add the same collection, multiple times

---

pages/pool/create.tsx
src/components/pools/whitelist/nft/NftWhiteListProcessSection.tsx
src/components/pureStyledComponents/text/Error.tsx
src/constants/pool.ts

AELIP-15: Hide limited per wallet on pool creation

---

src/components/pools/actions/Invest/NftsPickerModal.tsx

Closes #627 
Select All button is disabled if all NFTs are blacklisted

AELIP-15: [Bug] Select all button

---

src/components/pools/actions/Invest/NftsPickerModal.tsx
src/constants/contracts.ts

AELIP-15: [Bug] Unlimited deal single NFT selection

---

src/components/pools/actions/Invest/NftsPickerModal.tsx

Closes #625 
Created a new OwnedNfts component and wrap it with a genericSuspense

AELIP-15: [Bug] Loading spinner

---

pages/pool/create.tsx
src/components/pools/actions/Invest/Invest.tsx
src/components/pools/common/PoolCreateStepInput.tsx
src/components/pools/whitelist/WhiteListModal.tsx
src/constants/pool.ts
src/hooks/aelin/useAelinCreatePool.tsx
src/utils/validate/createPool.ts

https://user-images.githubusercontent.com/15804684/183985161-d44e5ef4-158b-4316-b753-7d78c78e9933.mov
Closes #624

AELIP-15: Add NFT as pool access option

---

src/components/pools/actions/Invest/NftsPickerModal.tsx

Closes #639 
Should not be possible to select blacklisted NFTs by clicking SelectAll button

AELIP-15: [Bug] Select all bug

---

src/hooks/aelin/useNftUserAllocation.tsx

Closes #645 
This PR solves the NFTSelection problem for rule `Limited per NFT`

AELIP-15: [Bug] Nftselection limited per nft

---

src/providers/nftSelectionProvider.tsx

AELIP-15: [Bug] Nftselection save

---

src/components/pools/actions/Deposit.tsx
src/providers/nftSelectionProvider.tsx

AELIP-15: [Bug] Clear State after deposit

---

src/components/form/TokenInput.tsx
src/components/pools/actions/Deposit.tsx
src/hooks/aelin/useNftUserAllocation.tsx
src/providers/nftSelectionProvider.tsx

AELIP-15: [Bug] Allocation error message and max button

---

src/components/pools/actions/Deposit.tsx
src/components/pools/actions/Invest/NftsPickerModal.tsx
src/providers/nftSelectionProvider.tsx

AELIP-15: [Bug] nftselection allocation decimals

---

src/components/pools/actions/Invest/NftsPickerModal.tsx
src/components/pools/whitelist/nft/NftCollection.tsx
src/components/pools/whitelist/nft/NftCollectionDetails.tsx
src/components/pools/whitelist/nft/NftCollectionInput.tsx
src/components/pools/whitelist/nft/NftCollectionsSection.tsx
src/components/pools/whitelist/nft/NftIdSelector.tsx
src/theme/darkTheme.ts
src/theme/lightTheme.ts

Improve pool creation responsiveness

---

src/components/pools/actions/Invest/nft/NftMedia.tsx
src/components/pools/actions/Invest/nft/OwnedNftsCarousel.tsx

AELIP-15: [Bug] owned nfts carousel

---

src/hooks/aelin/useNftCollectionList.tsx

AELIP-15: [Bug] Contract name

---

src/components/pools/actions/Invest/nft/OwnedNftsCarousel.tsx
src/components/pools/actions/Invest/nft/Shared.tsx
src/hooks/aelin/useNftCollectionList.tsx
src/hooks/aelin/useUserNftsByCollections.tsx
src/providers/nftSelectionProvider.tsx
src/services/nft/index.ts
src/utils/getNftType.ts

AELIP-15: [Feat] Add extra info

---

src/components/pools/actions/Invest/nft/NftCollectionRulesCarousel.tsx
src/components/pools/actions/Invest/nft/OwnedNftsCarousel.tsx
src/components/pools/actions/Invest/nft/Shared.tsx
src/hooks/aelin/useNftCollectionList.tsx

AELIP-15: [Bug] Selectnft modal responsiveness

---

src/components/pools/actions/Invest/nft/OwnedNftsCarousel.tsx
src/hooks/aelin/useNftUserAllocation.tsx

Closes #673
This PR also solves the problem with select all button

AELIP-15: [Bug] Nftselect modal erc1155

---

src/components/pools/actions/Invest/nft/OwnedNftsCarousel.tsx
src/components/pools/actions/Invest/nft/Shared.tsx

AELIP-15: [Feature] improve styling erc1155

---

pages/_app.tsx
src/components/pools/whitelist/WhiteListModal.tsx
src/providers/nftCreationState.tsx

AELIP-15: Add a React Context for NFT collections

---

src/components/pools/main/NftCollectionInformation.tsx
src/hooks/aelin/useNftCollectionLists.tsx

AELIP-15: [Bug] Nft collection table

---

src/components/pools/actions/Invest/nft/OwnedNftsCarousel.tsx
src/components/pools/main/NftCollectionInformation.tsx

Closes #680 
This PR also solves the problem with the NFT Collection table where `0 TokenSymbol` was shown instead of `Unlimited`

AELIP-15: [Bug] Selectall for erc721

---

src/hooks/aelin/useAelinCreatePool.tsx
src/hooks/common/usePrevious.tsx

AELIP-15: [Bug] Should wipe state

---

package.json
src/providers/web3ConnectionProvider.tsx
src/utils/getDefaultNetwork.ts
yarn.lock

Change wallet/network behavior

---

src/components/pools/common/PoolCreateStepInput.tsx
src/constants/misc.ts
src/utils/validate/createPool.ts

max lentgh to 30

---

src/components/pools/actions/Invest/nft/OwnedNftsCarousel.tsx

AELIP-15: [Bug] Fix No nft message

---

src/components/pools/list/Vouched.tsx

* Add NFT badge to verified pools

Add nft badge to verified pools (#699)

---

pages/stake/index.tsx
src/components/stake/StakeGrid.tsx
src/components/stake/StakeSection.tsx

* Enable to stake on pool 1
* Add Note for pool 1

Enable to stake on pool 1 (#703)

---

src/components/stake/StakeSection.tsx

Fix stake note (#706)

---

src/constants/contracts.ts

* Fix Stake Note
* Add new pool factories

Change aelin pool factory addresses (#708)

---

src/components/assets/SpinnerCSS.tsx
src/components/pools/actions/Invest/nft/NftMedia.tsx
src/components/pools/whitelist/nft/NftCollectionDetails.tsx

[Bug] Loading spinner overflows for small images

---

src/components/pools/list/List.tsx
src/components/pools/list/Vouched.tsx

* Fix Stake Note
* Temp fix: Use amount in pool value instead of funded

Fix - Use amountInPool value instead of funded (#722)

---

src/components/pools/list/List.tsx
src/components/pools/list/Vouched.tsx

* Fix Stake Note
* Temp fix: Use amount in pool value instead of funded
* Change column title

Change column title (#724)

---

src/constants/chains.tsx
src/hooks/aelin/useAelinTokenList.tsx

* Change token list source
* Use eth.limo instead of eth.link
* Add a fallback token list
* Fix limo url

Change token list source (#671)

---

src/utils/date.ts

Adds months to progress text

---

src/components/pools/PoolMain.tsx
src/components/pools/actions/Approve.tsx
src/components/pools/actions/FundDeal.tsx
src/components/pools/actions/Vest/ClaimUpfrontDealTokens.tsx
src/components/pools/actions/Vest/HasTokensToClaim.tsx
src/components/pools/actions/Vest/PoolSyncing.tsx
src/components/pools/actions/Vest/VestUpfrontDeal.tsx
src/components/pools/deal/UpfrontDealInformation.tsx
src/hooks/aelin/useAelinPool.tsx
src/hooks/aelin/useAelinPoolStatus.ts
src/utils/aelinPoolUtils.ts
types/aelinPool.ts

Bugs found during first group test for DDs
Closes #739

[Bug] Group test 1

---

src/components/pools/main/PoolInformation.tsx
src/constants/types.ts

[Bug] Deal deadline inconsistencies

---

src/hooks/aelin/useAelinPoolStatus.ts

AELIP-19: [Bug] User action box

---

src/abis/AelinUpfrontDeal.json
src/components/pools/actions/Deposit.tsx
src/hooks/aelin/merkle-tree/useAelinUserMerkleTreeData.tsx
src/hooks/aelin/useAelinPool.tsx
src/hooks/aelin/useMerkleTreeData.tsx
src/hooks/aelin/useUserAvailableToDeposit.tsx
src/queries/pools/fragments.ts
src/utils/aelinPoolUtils.ts

AELIP-38: Investor flow

---

src/components/common/ActionTabs.tsx
src/components/pools/actions/Approve.tsx
src/components/pools/actions/FundDeal.tsx
src/components/pools/actions/HolderDepositUpfrontDeal.tsx
src/components/pools/actions/Vest/ClaimUpfrontDealTokens.tsx
src/components/pools/actions/Vest/VestUpfrontDeal.tsx
src/components/pools/actions/Vest/VestingCompleted.tsx
src/components/pools/actions/Wrapper.tsx
src/constants/contracts.ts
src/hooks/aelin/useAelinCreateUpFrontDeal.tsx

AELIP-38 - Add Investor flow improvements

---

src/constants/misc.ts
src/utils/aelinPoolUtils.ts

Fix display decimals

---

src/components/pools/deal/UpfrontDealInformation.tsx

* Fix deal exchange rate
* Fix deal exchange rate

Fix deal exchange rates (#788)

---

src/components/pools/deal/DealInformation.tsx

Reverts AelinXYZ/aelin-frontend-v2#785

Revert "Fix deal exchange rate"

---

src/components/pools/actions/Deposit/Deposit.tsx
src/components/pools/actions/Deposit/DepositDirectDeal.tsx
src/components/pools/actions/Invest/nft/OwnedNftsCarousel.tsx
src/constants/misc.ts
src/hooks/aelin/useAelinCreatePool.tsx
src/hooks/aelin/useAelinCreateUpFrontDeal.tsx
src/hooks/aelin/useAelinPools.tsx
src/hooks/aelin/useNftUserAllocation.tsx
src/providers/nftSelectionProvider.tsx
src/services/nft/index.ts
src/utils/aelinPoolUtils.ts

* Fix display decimals
* Hide a pool
* filter pool
* Fix purchase amount decimals
Co-authored-by: 0xcdb <90234851+0xcdb@users.noreply.github.com>
Co-authored-by: alextheboredape <89657259+alextheboredape@users.noreply.github.com>

Decimals fixes

---

src/hooks/aelin/useAelinPools.tsx
src/utils/isHiddenPool.ts

* Fix display decimals
* Hide a pool
* filter pool
* hide test pools
Co-authored-by: 0xcdb <90234851+0xcdb@users.noreply.github.com>
Co-authored-by: alextheboredape <89657259+alextheboredape@users.noreply.github.com>

Hide test pools (#808)

---

src/components/pools/deal/DealInformation.tsx
src/components/pools/deal/UpfrontDealInformation.tsx

This PR closes #_, by:
- Updating 'a'
- Adding 'b'

fix: hidden explorer link if the pool's deal address is empty.

---

pages/index.tsx
src/components/common/CollapsibleBlock.tsx
src/components/common/DynamicDeadline.tsx
src/components/layout/Header.tsx
src/components/navigation/TopMenu.tsx
src/components/pools/actions/Invest/nft/NftCollectionRulesCarousel.tsx
src/components/pools/list/List.tsx
src/components/pools/list/Vouched.tsx
src/components/section/SectionIntro.tsx

Closes #817
Fixed UI bugs related to:
- Website header
- Create deal/pool sections
- Pools list table
- Hide My pools and Aelin sections by default on smaller screen sizes

Fix ipad responsiveness

---

src/constants/types.ts

Rename “Deal Deadline” box in the pool timeline to "Holder Funding Deadline"

---

src/hooks/aelin/useAelinPoolStatus.ts

Fix double "Withdraw" tab in pool user actions

---

src/hooks/aelin/useAelinPoolStatus.ts

“Deal Creation” box enhancement

---

src/constants/misc.ts
src/utils/formatNumber.ts
src/web3/bigNumber.ts

Display 4 decimals if the number is less than 1

---

src/components/pools/actions/WithdrawUnredeemed.tsx
src/hooks/aelin/useAelinPool.tsx
src/utils/aelinPoolUtils.ts

Use the largest decimal between token decimals when doing math

---

src/components/pools/actions/Deposit/Deposit.tsx
src/components/pools/actions/Deposit/DepositDirectDeal.tsx

Closes https://github.com/AelinXYZ/aelin-frontend-v2/issues/862

Disable deposit in hidden pools

---

src/components/pools/whitelist/WhiteListModal.tsx
src/components/pools/whitelist/addresses/AddressesWhiteList.tsx

Add duplicated addresses warning to the Allowlist modal

---

src/components/pools/list/Vouched.tsx
src/hooks/aelin/vouched-pools/useAelinVouchedPools.tsx
src/hooks/aelin/vouched-pools/useVoucherAddress.tsx
src/hooks/useEnsResolvers.tsx

[Bug] fix vouched pools flickering

---

.github/workflows/ci.yml

Add unit tests to GitHub Actions

---

src/hooks/aelin/useMerkleTreeData.tsx

Add extra try-catch to merkle fallback

---

src/hooks/aelin/useMerkleTreeData.tsx

Wrong allowance amount in UI until refresh for merkle tree deals

---

src/components/pools/common/DealCreateStepInput.tsx
src/hooks/aelin/useAelinCreateUpFrontDeal.tsx

Select capped deal by default

---

src/components/sidebar/BuyAelin.tsx
src/hooks/aelin/useAelinUSDPrice.ts

Sidebar - Improve Aelin Price 

---

src/components/pools/whitelist/addresses/AddressesWhiteList.tsx

Add "Total addresses" to allowlist modal

---

src/components/pools/actions/HolderDeposit/HolderDeposit.tsx
src/components/pools/actions/HolderDeposit/HolderDepositUpfrontDeal.tsx

Add error message when holder does not have enough to fund the deal

---

src/utils/validate/createDirectDeal.ts

Handle silent errors in the UI during deal creation

---

src/hooks/aelin/useAelinCreateUpFrontDeal.tsx
src/utils/parseValuesToCreateUpFrontDeal.ts
src/utils/validate/createDirectDeal.ts

Exception on deal creation screen if exchange rate is too small

---

src/components/pools/PoolMain.tsx
src/hooks/aelin/usePoolSupportsMethod.tsx

Vouched Pools: Hide vouch action box for old pools

---

src/components/common/DynamicDeadline.tsx

Fix Vesting Period progress bar

---

codegen-custom-naming.js
codegen.js

[BUG] Custom name generator for GraphQL codegen

---

src/hooks/aelin/vouched-pools/usePoolVouchers.tsx

[Vouched Pool] vouch modals infinite loop

---

src/components/aelin/ENSOrAddress.tsx
src/components/pools/actions/Vouch/VouchersModal.tsx
src/hooks/useEnsResolvers.tsx

Improve ENSOrAddress component

---

src/components/pools/common/InvestorsModal.tsx
src/components/pureStyledComponents/common/Badge.tsx
src/components/pureStyledComponents/common/InlineLoading.tsx
src/hooks/requiredConnection.tsx

Improve some font sizes  (#967)

---

src/components/pools/actions/Approve.tsx
src/components/pools/actions/FundDeal.tsx

Add error message when holder does not have enough to fund the deal (approve action)

---

src/hooks/aelin/useNftCollectionLists.tsx
src/services/nft/index.ts

Verify NFT ownership on Goerli

---

src/components/stats/List.tsx
src/constants/contracts.ts
src/hooks/aelin/history/useAelinDealsAccepted.tsx
src/hooks/aelin/useAelinPool.tsx
src/hooks/aelin/useNftCollectionLists.tsx
src/queries/pools/fragments.ts
src/services/nft/index.ts
src/utils/aelinPoolUtils.ts
src/utils/validate/createDirectDeal.ts

This PR is related to this commit on the subgraph repo: https://github.com/AelinXYZ/aelin-subgraph/pull/111/commits/dfbfe2251b6cae6a4a5dfa7d73b62db75e851a37

Adapt types to new version of Subgraph AssemblyScript

---

src/components/sidebar/BuyAelin.tsx

This fixes issue #544 by adding `margin-bottom: 15px` to the `Wrapper` div.

Fix Buy Aelin Button shadow cropped (issue #544)

---

src/components/layout/Header.tsx

Fix Lizards header on mobile

---

src/components/toast/ToastComponent.tsx

Fix toast message overflow

---

src/components/pools/PoolMain.tsx
src/components/pools/common/Create.tsx

Small layout fixes

---

src/utils/stake/getUniswapStakingRewards.ts

Reverts AelinXYZ/aelin-frontend-v2#1048

Revert "temp fix due to uniswap v2 subgraph issues"
